version: '3.7'

services:
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application
    environment:
      - TZ="Asia/Seoul"
    restart: 'unless-stopped'
    networks:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Seoul"
    ports:
      - '3306:3306'
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend

  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      - TZ="Asia/Seoul"
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge